import { useEffect, useState, type FormEvent } from 'react'
import type { SupabaseRest } from '../../shared/api/supabase'
import type { ContextDraft, Patient } from '../../shared/types/domain'
import { CONTEXT_LABELS } from '../../shared/types/constants'
import { EmptyState } from '../../shared/components/EmptyState'
import { StatusMessage } from '../../shared/components/StatusMessage'
import { hospitalApi } from '../api/hospitalApi'

export function ContextApproval({ api, token, userId, patient }: { api: SupabaseRest; token: string; userId: string | null; patient: Patient }) {
  const [drafts, setDrafts] = useState<ContextDraft[]>([]); const [category, setCategory] = useState('hospital'); const [text, setText] = useState(''); const [source, setSource] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [uncertain, setUncertain] = useState(false)
  async function reload() { setDrafts(await hospitalApi.contextDrafts(api, token, patient)) }
  useEffect(() => { void reload().catch(() => setStatus('승인 대기 맥락을 읽지 못했습니다.')) }, [api, token, patient])
  async function reconcile() { setBusy(true); try { await reload(); setUncertain(false); setStatus('서버 기록을 다시 읽었습니다. 중복 여부를 확인한 뒤 작업하세요.') } catch { setStatus('서버 기록을 읽지 못했습니다. 제출과 승인을 계속 잠급니다.') } finally { setBusy(false) } }
  async function submit(event: FormEvent) { event.preventDefault(); if (uncertain || !patient.encounter_id || !text.trim() || !/^TEST-[A-Z0-9_-]{1,50}$/.test(source)) return setStatus('원문 200자 제한과 TEST- 합성 출처를 확인하세요.'); if (drafts.some(draft => draft.proposed_by_auth_user_id === userId && draft.category === category && draft.proposed_text === text.trim() && draft.source_ref === source)) return setStatus('같은 병원 맥락 제안이 이미 승인 대기 중입니다.'); setBusy(true); try { await hospitalApi.createContextDraft(api, token, { patient_id: patient.patient_id, encounter_id: patient.encounter_id, category, proposed_text: text.trim(), source_ref: source }); setText(''); setSource(''); await reload(); setStatus('병원 맥락 제안을 기록했습니다. 다른 담당 직원의 승인이 필요합니다.') } catch { setUncertain(true); setStatus('제안 등록 결과를 확인하지 못했습니다. 서버 기록을 다시 읽기 전에는 재등록하지 마세요.') } finally { setBusy(false) } }
  async function approve(draft: ContextDraft) { if (uncertain || !userId || draft.proposed_by_auth_user_id === userId) return; setBusy(true); try { await hospitalApi.approveContextDraft(api, token, draft.draft_id); const [approved, facts] = await Promise.all([hospitalApi.approvedContextDraft(api, token, draft.draft_id), hospitalApi.approvedContextFact(api, token, draft.draft_id, patient.patient_id)]); const row = approved[0], fact = facts[0]; if (approved.length !== 1 || row.status !== 'approved' || row.approved_by_auth_user_id !== userId || row.patient_id !== patient.patient_id || row.encounter_id !== patient.encounter_id || row.category !== draft.category || row.proposed_text !== draft.proposed_text || row.source_ref !== draft.source_ref || facts.length !== 1 || fact.fact_id !== draft.draft_id || fact.content !== draft.proposed_text || fact.synthetic_source_ref !== draft.source_ref) throw new Error('unconfirmed approval'); await reload(); setStatus('맥락 승인과 현재 병원 사실 기록을 DB에서 확인했습니다.') } catch { setUncertain(true); setStatus('승인 결과를 확인하지 못했습니다. 서버 기록을 다시 읽기 전에는 작업하지 마세요.') } finally { setBusy(false) } }
  return <div>{uncertain && <button onClick={() => void reconcile()} disabled={busy}>서버 기록 다시 읽고 작업 잠금 해제</button>}<form className="form-stack" onSubmit={submit}><label>정보 종류<select value={category} onChange={e => setCategory(e.target.value)}>{['hospital','ward','room','test_schedule','visit_schedule'].map(value => <option key={value} value={value}>{CONTEXT_LABELS[value]}</option>)}</select></label><label>확인한 원문<textarea required maxLength={200} value={text} onChange={e => setText(e.target.value)}/></label><label>합성 출처 참조<input required maxLength={55} placeholder="TEST-HOSPITAL-975" value={source} onChange={e => setSource(e.target.value.toUpperCase())}/></label><button className="primary" disabled={busy || uncertain}>합성 맥락 제안 등록</button></form><h3>다른 담당 직원의 승인 대기</h3>{!drafts.length ? <EmptyState>승인 대기 제안이 없습니다.</EmptyState> : <ul className="item-list">{drafts.map(d => <li className="item" key={d.draft_id}><div className="item-title">{CONTEXT_LABELS[d.category]}</div><p>{d.proposed_text}</p><div className="item-meta">{d.source_ref}</div><button disabled={busy || uncertain || d.proposed_by_auth_user_id === userId} onClick={() => void approve(d)}>{d.proposed_by_auth_user_id === userId ? '본인 제안은 승인할 수 없음' : '맥락 승인'}</button></li>)}</ul>}<StatusMessage tone={uncertain ? 'warning' : 'info'}>{status}</StatusMessage></div>
}
