import { useEffect, useState, type FormEvent } from 'react'
import type { SupabaseRest } from '../../shared/api/supabase'
import type { MessageDraft, Patient } from '../../shared/types/domain'
import { EmptyState } from '../../shared/components/EmptyState'
import { StatusMessage } from '../../shared/components/StatusMessage'
import { hospitalApi } from '../api/hospitalApi'
import { formatHospitalTime } from '../utils/format'

export function MessageApproval({ api, token, userId, patient }: { api: SupabaseRest; token: string; userId: string | null; patient: Patient }) {
  const [drafts, setDrafts] = useState<MessageDraft[]>([]); const [text, setText] = useState(''); const [mode, setMode] = useState('now'); const [time, setTime] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false)
  async function reload() { setDrafts(await hospitalApi.messageDrafts(api, token, patient)) }
  useEffect(() => { void reload().catch(() => setStatus('승인 대기 초안을 읽지 못했습니다.')) }, [api, token, patient])
  async function submit(event: FormEvent) { event.preventDefault(); if (!patient.encounter_id || !text.trim() || text.length > 200) return; const body: Record<string, unknown> = { patient_id: patient.patient_id, encounter_id: patient.encounter_id, proposed_text: text.trim(), schedule_mode: mode }; if (mode === 'scheduled') { const due = new Date(`${time}:00+09:00`); if (!time || due <= new Date()) return setStatus('한국 시간 기준 앞으로의 예약 시각을 입력하세요.'); body.requested_due_at = due.toISOString() } setBusy(true); try { await hospitalApi.createMessageDraft(api, token, body); setText(''); setTime(''); await reload(); setStatus('원문 초안을 기록했습니다. 다른 담당 직원의 승인이 필요합니다.') } catch { setStatus('초안 등록 결과를 확인하지 못했습니다. 기록을 확인하기 전에는 재등록하지 마세요.') } finally { setBusy(false) } }
  async function approve(draft: MessageDraft) { if (!userId || draft.proposed_by_auth_user_id === userId) return; setBusy(true); try { await hospitalApi.approveMessageDraft(api, token, draft.draft_id); const [approved, queued] = await Promise.all([hospitalApi.approvedMessageDraft(api, token, draft.draft_id), hospitalApi.queuedMessage(api, token, draft.draft_id)]); if (approved.length !== 1 || approved[0].status !== 'approved' || approved[0].approved_by_auth_user_id !== userId || approved[0].proposed_text !== draft.proposed_text || queued.length !== 1 || queued[0].approved_text !== draft.proposed_text || queued[0].delivery_status !== 'pending' || queued[0].encounter_id !== patient.encounter_id) throw new Error('unconfirmed approval'); await reload(); setStatus('원문 승인과 전달 대기 기록을 DB에서 확인했습니다.') } catch { setStatus('승인 결과를 확인하지 못했습니다. 환자를 다시 선택해 확인하세요.') } finally { setBusy(false) } }
  return <div><form className="form-stack" onSubmit={submit}><label>승인할 원문<textarea required maxLength={200} value={text} onChange={e => setText(e.target.value)}/></label><label>전달 예약<select value={mode} onChange={e => setMode(e.target.value)}><option value="now">승인 직후 대기</option><option value="scheduled">시각 예약</option></select></label>{mode === 'scheduled' && <label>예약 시각 (한국 시간)<input type="datetime-local" required value={time} onChange={e => setTime(e.target.value)}/></label>}<button className="primary" disabled={busy}>합성 원문 초안 등록</button></form><h3>다른 담당 직원의 승인 대기</h3>{!drafts.length ? <EmptyState>승인 대기 원문이 없습니다.</EmptyState> : <ul className="item-list">{drafts.map(d => <li className="item" key={d.draft_id}><p>{d.proposed_text}</p><div className="item-meta">{d.schedule_mode === 'scheduled' ? formatHospitalTime(d.requested_due_at) : '승인 직후 대기'}</div><button disabled={busy || d.proposed_by_auth_user_id === userId} onClick={() => void approve(d)}>{d.proposed_by_auth_user_id === userId ? '본인 초안은 승인할 수 없음' : '원문 승인'}</button></li>)}</ul>}<StatusMessage>{status}</StatusMessage></div>
}
