import { useEffect, useRef, useState } from 'react'
import type { SupabaseRest } from '../../shared/api/supabase'
import type { Patient } from '../../shared/types/domain'
import { StatusMessage } from '../../shared/components/StatusMessage'
import { hospitalApi } from '../api/hospitalApi'

export function StaffVoiceTrial({ api, token, patient }: { api: SupabaseRest; token: string; patient: Patient }) {
  const [active, setActive] = useState(false); const [ready, setReady] = useState(false); const [started, setStarted] = useState(0); const [duration, setDuration] = useState(0); const [status, setStatus] = useState('합성 준비 조건을 확인하고 있습니다.'); const stream = useRef<MediaStream | null>(null); const timer = useRef<number | null>(null)
  function release(reason = '직원이 중단') { if (timer.current) window.clearTimeout(timer.current); timer.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; if (active) setDuration(Math.min(30, (Date.now() - started) / 1000)); setActive(false); setStatus(`${reason}. 마이크를 중단하고 오디오 참조를 해제했습니다. 추가 보관·전송하지 않습니다.`) }
  async function checkReady() { try { const rows = await hospitalApi.rpc<Array<{ patient_id: string; ready: boolean; voice_profile_state: string }>>(api, token, 'synthetic_voice_enrollment_ready'); const ok = rows.length === 1 && rows[0].patient_id === patient.patient_id && rows[0].ready === true; setReady(ok); setStatus(ok ? '시험자 본인 음성으로만 30초 이내 마이크 시험을 시작할 수 있습니다.' : '합성 준비 조건이 충족되지 않았습니다.') } catch { setReady(false); setStatus('합성 음성 시험 준비 결과를 확인하지 못했습니다.') } }
  useEffect(() => { const hide = () => { if (document.hidden) release('화면 숨김') }; document.addEventListener('visibilitychange', hide); void checkReady(); return () => { document.removeEventListener('visibilitychange', hide); release('화면 이동') } }, [api, token, patient])
  async function start() { if (!ready || active) return; setStatus('직원 자격을 다시 확인하고 마이크 권한을 요청합니다.'); try { const rows = await hospitalApi.rpc<Array<{ patient_id: string; ready: boolean }>>(api, token, 'synthetic_voice_enrollment_ready'); if (rows.length !== 1 || rows[0].patient_id !== patient.patient_id || rows[0].ready !== true) { setReady(false); return setStatus('합성 준비 상태가 바뀌어 마이크를 열지 않았습니다.') } const media = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); stream.current = media; setStarted(Date.now()); setDuration(0); setActive(true); setStatus('시험자 본인 음성을 메모리에서만 녹음 중입니다.'); timer.current = window.setTimeout(() => release('30초 시험 상한 도달'), 30000) } catch { release('마이크 권한 또는 브라우저 녹음 기능 확인 실패') } }
  return <div><p className="compact">담당 직원이 자신의 목소리로만 시험합니다. 실제 환자·주변인 음성은 녹음하지 마세요.</p><div className="button-row"><button disabled={!ready || active} onClick={() => void start()}>본인 음성 시험 시작</button><button disabled={!active} onClick={() => release()}>중단하고 오디오 참조 해제</button></div><p>{active ? '마이크 시험 중 · 최대 30초' : `${duration.toFixed(1)}초 / 최대 30초`}</p><StatusMessage>{status}</StatusMessage></div>
}
